# Generated by Django 2.0.2 on 2018-06-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_ranks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
    ]
