# Generated by Django 2.0.2 on 2018-07-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180725_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pilot',
        ),
    ]
