# Generated by Django 4.0.3 on 2022-03-17 21:29

from django.db import migrations

def fill_ranks(apps, schema_editor):
    Rank = apps.get_model("stats", "Rank")
    ranks = ["Guest"]
    ranks = ranks + ["O" + str(rank) for rank in range(1,7)]
    print(ranks)
    for rank in ranks:
        Rank.objects.create(rank=rank)


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_userprofile_pilot'),
    ]

    operations = [
        migrations.RunPython(fill_ranks)
    ]
