# Generated by Django 2.0.2 on 2018-06-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20180617_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='pilot_id',
        ),
    ]
