# Generated by Django 2.0.2 on 2018-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_slmod_total_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slmod_total',
            name='file',
            field=models.FileField(upload_to='SlmodStats/'),
        ),
    ]
