# Generated by Django 2.0.2 on 2018-06-19 15:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20180618_1706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aircraft',
            managers=[
                ('create', django.db.models.manager.Manager()),
            ],
        ),
    ]
