# Generated by Django 2.0.2 on 2018-06-29 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20180626_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 14, 8, 11, 983337)),
        ),
    ]
