# Generated by Django 2.0.2 on 2018-06-30 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0029_auto_20180629_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 29)),
        ),
    ]
