# Generated by Django 2.0.2 on 2018-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0054_auto_20180716_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
