# Generated by Django 2.0.2 on 2018-07-18 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0064_stats_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='all_aircraft_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='building_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='crash',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='death',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='eject',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='fighter_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='friendly_col_hits',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='friendly_col_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='friendly_hits',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='friendly_kills',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='heli_kills',
        ),
        migrations.AddField(
            model_name='stats',
            name='aar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='aircraft_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='landings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='traps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='in_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='rank_id',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Rank'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ground_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='in_air_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ship_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
