# Generated by Django 2.0.2 on 2018-06-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientid", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=50)),
                ("callsign", models.CharField(max_length=30)),
            ],
        ),
    ]
