# Generated by Django 2.0.2 on 2018-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20180617_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='id',
        ),
        migrations.AlterField(
            model_name='pilot',
            name='clientid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
