# Generated by Django 2.0.2 on 2018-06-18 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_auto_20180617_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="pilot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stats.Pilot",
            ),
        ),
    ]
