# Generated by Django 2.0.2 on 2018-06-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_rank_pilot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_air", models.IntegerField()),
            ],
        ),
    ]
