# Generated by Django 2.0.2 on 2018-06-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_slmod_totals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slmod_Totals',
            new_name='Slmod_Total',
        ),
    ]
