# Generated by Django 2.0.2 on 2018-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0015_auto_20180617_1949"),
    ]

    operations = [
        migrations.AddField(
            model_name="slmod_total",
            name="name",
            field=models.CharField(default="slmod", max_length=30),
            preserve_default=False,
        ),
    ]
