# Generated by Django 2.0.2 on 2018-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0019_remove_total_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="aircraft",
            field=models.CharField(default="L-39C", max_length=50),
            preserve_default=False,
        ),
    ]
