# Generated by Django 2.0.2 on 2018-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0020_aircraft_aircraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="aircraft",
            field=models.TextField(),
        ),
    ]
