# Generated by Django 2.0.2 on 2018-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_auto_20180618_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft',
            field=models.CharField(max_length=30),
        ),
    ]
