# Generated by Django 2.0.2 on 2018-06-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_auto_20180619_1031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aircraft',
            managers=[
            ],
        ),
    ]
