# Generated by Django 2.0.2 on 2018-06-29 19:38

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0026_aircraft_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft", models.CharField(max_length=30)),
                ("in_air_sec", models.FloatField()),
                ("total_sec", models.FloatField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2018, 6, 29, 14, 38, 17, 27803)
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.Pilot"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 6, 29, 14, 38, 17, 26787)
            ),
        ),
    ]
