# Generated by Django 2.0.2 on 2018-06-29 19:53

import datetime

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0027_auto_20180629_1438"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="mission",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 6, 29, 14, 53, 21, 446607)
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2018, 6, 29, 14, 53, 21, 446607)
            ),
        ),
    ]
