# Generated by Django 2.0.2 on 2018-06-30 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_auto_20180629_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 2, 55, 40, 94843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 2, 55, 40, 95844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=models.CharField(max_length=100),
        ),
    ]
