# Generated by Django 2.0.2 on 2018-07-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0035_remove_aircraft_pilot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraft",
            name="id",
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="aircraft",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
