# Generated by Django 2.0.2 on 2018-07-01 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0037_auto_20180630_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="aircraft",
            field=models.ForeignKey(
                default="AV8BNA",
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.Aircraft",
            ),
            preserve_default=False,
        ),
    ]
