# Generated by Django 2.0.2 on 2018-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_auto_20180710_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='file',
            field=models.CharField(default='UNK', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='all_aircraft_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='building_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='crash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='death',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='eject',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='fighter_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='friendly_col_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='friendly_col_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='friendly_hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='friendly_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ground_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='heli_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='in_air_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ship_kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='total_sec',
            field=models.FloatField(null=True),
        ),
    ]
