# Generated by Django 2.0.2 on 2018-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0045_auto_20180711_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="ip_flag",
            field=models.IntegerField(default=0),
        ),
    ]
