# Generated by Django 2.0.2 on 2018-07-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0047_auto_20180711_2137"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mission",
            new_name="Stats",
        ),
    ]
