# Generated by Django 2.0.2 on 2018-07-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0048_auto_20180715_1035"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("date", models.DateTimeField()),
                ("file", models.CharField(max_length=100)),
                ("ip_flag", models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stats",
            name="date",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="file",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="ip_flag",
        ),
        migrations.AlterField(
            model_name="stats",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.Mission"
            ),
        ),
    ]
