# Generated by Django 2.0.2 on 2018-07-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0049_auto_20180715_1041"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="stats",
            managers=[],
        ),
    ]
