# Generated by Django 2.0.2 on 2018-07-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0058_remove_stats_pilot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stats",
            name="aircraft",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="mission",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
