# Generated by Django 2.0.2 on 2018-07-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0060_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("losses", models.IntegerField(default=0)),
                ("aircraft_kills", models.IntegerField(default=0)),
                (
                    "stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.Stats"
                    ),
                ),
            ],
        ),
    ]
