# Generated by Django 2.0.2 on 2018-07-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0065_auto_20180717_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stats",
            name="new",
            field=models.IntegerField(default=1),
        ),
    ]
